### ISSUE TITLE
[Select]: If there are multiple Select components, clicking on the label text of a Select component will open the first Select components dropdown list 

### ISSUE THREAD

**Issue by matthew-hogains** [narmi/design_system#880] opened 2023-02-08 17:53 UTC
### Component/Module
Select (could include dropdown but no entirely sure)

### Screenshots (if applicable)

https://user-images.githubusercontent.com/71462029/217611957-b61ffd54-ef43-464e-ba1a-92a758f5c55d.mov

### Reproduction Steps
1. add multiple Select components with labels
2. click the label of any non first Select component
3. the dropdown of the first Select will open
### Expected Result
the Select component clicked should open its drop down
### Actual Result
the first Select component dropdown opens

**Comment by reshav-abraham** [comment] 2023-02-17 16:38
Dupe of https://github.com/narmi/design_system/issues/882 @matthew-hogains please re-open if this is still an issue. I didn't encounter this when I ran the product wizard

**Closed by reshav-abraham** 2023-02-17 16:38 UTC
Labels: bug, Platform
