### ISSUE TITLE
[Tooltip] support multi-line text

### ISSUE THREAD

**Issue by xiexiewenting** [narmi/design_system#682] opened 2022-04-12 18:39 UTC
<img width="500" alt="figma" src="https://user-images.githubusercontent.com/54218373/163030437-db8f386c-ee36-43f5-9d33-051de039a94c.png">

Came out of https://github.com/narmi/banking/issues/17868; some designs in `banking` call for tooltips that should be rendered as 2 lines

**Comment by akdetrick** [comment] 2022-04-12 19:36
We have to be careful with this - there are a few ways we can get this wrong.

### Options
1. continue to use `width` to break text and/or limit the tooltip width
2. change `label` to accept arbitrary JSX in order to insert `<br />` or divs

Option 1 is bad because we are copyfitting, which is problematic in general, made worse by the fact that translation strings of different lengths may appear in the tooltip.

Option 2 is bad because it increases the API surface area of the component and makes it more brittle to change and design inconsistencies.

### Questions to answer

Why is it important from a design standpoint to break the text at an exact point? 

If it is simply limiting width, we can just use the existing `width` prop. If it is for aesthetics, then we must support arbitrary JSX and accept the tradeoff of opening the door to more variability in visual presentation

**Comment by akdetrick** [comment] 2022-04-25 20:11
**Decision:** 
We will use `maxWidth` to control wrapping. Translated text will fall within the same tooltip width that we set based on English copy.

This issue is now a duplicate of the bug fix that allows us to move forward with using width to control wrapping:
- #697

**Closed by akdetrick** 2022-04-25 20:11 UTC
Labels: Platform, Needs Design
